library(data.table)
consumption <- fread("household_power_consumption.txt")
data <- consumption[66637:69516,]
date<-as.POSIXct(paste(data$Date,data$Time), format="%d/%m/%Y %H:%M:%S")
png(filename="plot3.png",width=480,height=480,pointsize = 12)
plot(date,data$Sub_metering_1,type="n",xlab=" ",ylab="Energy sub metering ")
lines(date,data$Sub_metering_1)
lines(date,data$Sub_metering_2,col='red')
lines(date,data$Sub_metering_3,col='blue')
legend("topright", lty=1,c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c('black', 'red','blue' ), cex=.75)
dev.off()
